import { Schema } from "mongoose"

export default new Schema<iOrder>(
    {
        positionId: { type: String, required: true, unique: false },
        id: { type: String, required: true, unique: false },
        orderDateTime: { type: String, required: true, unique: false },
        orderId: { type: String, required: true, unique: false },
        exchOrdId: { type: String, required: true, unique: false },
        side: { type: Number, required: true, unique: false },
        segment: { type: Number, required: true, unique: false },
        instrument: { type: String, required: true, unique: false },
        productType: { type: String, required: true, unique: false },
        status: { type: Number, required: true, unique: false },
        qty: { type: Number, required: true, unique: false },
        remainingQuantity: { type: Number, required: true, unique: false },
        filledQty: { type: Number, required: true, unique: false },
        limitPrice: { type: Number, required: true, unique: false },
        stopPrice: { type: Number, required: true, unique: false },
        type: { type: Number, required: true, unique: false },
        discloseQty: { type: Number, required: true, unique: false },
        dqQtyRem: { type: Number, required: true, unique: false },
        orderValidity: { type: String, required: true, unique: false },
        source: { type: String, required: true, unique: false },
        slNo: { type: Number, required: true, unique: false },
        fyToken: { type: String, required: true, unique: false },
        offlineOrder: { type: Boolean, required: true, unique: false },
        message: { type: String, required: true, unique: false },
        orderNumStatus: { type: String, required: true, unique: false },
        tradedPrice: { type: Number, required: true, unique: false },
        exchange: { type: Number, required: true, unique: false },
        pan: { type: String, required: true, unique: false },
        clientId: { type: String, required: true, unique: false },
        symbol: { type: String, required: true, unique: false },
        ch: { type: String, required: true, unique: false },
        chp: { type: String, required: true, unique: false },
        lp: { type: String, required: true, unique: false },
        ex_sym: { type: String, required: true, unique: false },
        description: { type: String, required: true, unique: false },
    },
    { timestamps: true },
)
