import { Schema } from "mongoose"

export default new Schema<iSymbolTicks>(
	{
		highPrice: { type: Number },
		prevClosePrice: { type: Number },
		ch: { type: Number },
		tt: { type: Number },
		description: { type: String },
		shortName: { type: String },
		exchange: { type: String },
		lowPrice: { type: Number },
		cmd: {
			c: { type: Number },
			h: { type: Number },
			l: { type: Number },
			o: { type: Number },
			t: { type: Number },
			v: { type: Number },
			tf: { type: String },
		},
		originalName: { type: String },
		chp: { type: Number },
		openPrice: { type: Number },
		lp: { type: Number },
		symbol: { type: String },
		LTQ: { type: Number },
		L2LTT: { type: Number },
		ATP: { type: Number },
		volume: { type: Number },
		totBuy: { type: Number },
		totSell: { type: Number },
		bid: { type: Number },
		ask: { type: Number },
		spread: { type: Number },
		marketStat: { type: Number },
	},
	{ timestamps: true },
)
